name: Deploy GitHub Pages for master and dev

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare Master Deployment
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p public
          rsync -av --exclude=.git --exclude=public ./ public/
          touch public/.nojekyll
          echo "Master branch deployed to /"

      - name: Prepare Dev Deployment
        if: github.ref == 'refs/heads/dev'
        run: |
          mkdir -p public/dev
          rsync -av --exclude=.git --exclude=public ./ public/dev/
          touch public/.nojekyll
          echo "Dev branch deployed to /dev"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
