name: Deploy GitHub Pages for master and dev

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build and Deploy Master
        if: github.ref == 'refs/heads/master'
        run: | 
          cp -r * ./
          touch .nojekyll
          echo "Master branch deployed"

      - name: Build and Deploy Dev
        if: github.ref == 'refs/heads/dev'
        run: |
          mkdir -p dev
          cp -r * dev/
          touch dev/.nojekyll
          echo "Dev branch deployed to /dev"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./

  deploy-pages:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
